apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: pythonapp
        image: docker.io/8087180718/python-app:0.1
        ports:
        - containerPort: 80
        env:
        - name: FILE_PATH
          value: "/app/emp-data.xlsx"
